### ISSUE TITLE
Solaris 10 i386 agent package build check fail

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh-packages#1794] opened 2022-08-22 14:10 UTC
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| v4.5.0 | Agent | Install | Solaris 10 |

The following PR https://github.com/wazuh/wazuh/pull/14524 failed checking the Solaris 10 i386 agent package build. The PR seeks to merge into `master` branch from the `feature/14087-aws-find-account-ids-error-management` branch.

## Details
```
10:14              "    solaris10_gcc9: /bin/sh: test: argument expected",
15:10:14              "    solaris10_gcc9: test -d external/curl ||\\",
15:10:14              "    solaris10_gcc9: (curl -so external/curl.tar.gz https://packages.wazuh.com/deps/18/libraries/sources/curl.tar.gz &&\\",
15:10:14              "    solaris10_gcc9: cd external && gunzip curl.tar.gz && tar -xf curl.tar && rm curl.tar)",
15:10:14              "    solaris10_gcc9: gmake: [Makefile:1262: external-precompiled/curl.tar.gz] Error 1 (ignored)",
15:10:14              "    solaris10_gcc9: gmake: *** [Makefile:1246: external/curl.tar.gz] Error 35",
15:10:14              "    solaris10_gcc9: grep: can't open /etc/os-release",
15:10:14              "    solaris10_gcc9: cd external/zlib/ && CFLAGS=-fPIC ./configure && gmake libz.a",
15:10:14              "    solaris10_gcc9: /bin/sh: external/zlib/: does not exist",
15:10:14              "    solaris10_gcc9: gmake: *** [Makefile:926: external/zlib//libz.a] Error 1",
15:10:14              "    solaris10_gcc9: gmake: *** Waiting for unfinished jobs....",
15:10:14              "    solaris10_gcc9:     \u001b[34mCC\u001b[0m \u001b[33mexternal/cJSON/cJSON.o\u001b[0m",
15:10:14              "    solaris10_gcc9: find: stat() error /var/ossec: No such file or directory",
15:10:14              "    solaris10_gcc9: v4.5.0",
15:10:14              "    solaris10_gcc9: ## Building pkgmap from package prototype file.",
15:10:14              "    solaris10_gcc9: ERROR in wazuh-agent_v4.5.0.proto:",
15:10:14              "    solaris10_gcc9:     no object for </etc/init.d/wazuh-agent> found in root directory",
15:10:14              "    solaris10_gcc9: pkgmk: ERROR: unable to build pkgmap from prototype file",
15:10:14              "    solaris10_gcc9: ## Packaging was not successful.",
15:10:14              "    solaris10_gcc9: pkgtrans: ERROR: unable to complete package transfer",
15:10:14              "    solaris10_gcc9:     - no packages were selected from </export/home/vagrant/build/solaris10>",
15:10:14              "    solaris10_gcc9: mv: cannot access wazuh-agent_v4.5.0-sol10-i386.pkg",
15:10:14              "    solaris10_gcc9: /opt/csw/gnu/sha512sum: wazuh-agent_v4.5.0-sol10-i386.pkg: No such file or directory",
15:10:14              "    solaris10_gcc9: ./generate_wazuh_packages.sh: line 262: /var/ossec/bin/wazuh-control: No such file or directory",
15:10:14              "    solaris10_gcc9: /var/ossec*: No such file or directory",
15:10:14              "    solaris10_gcc9: ./generate_wazuh_packages.sh: line 262: /var/ossec/bin/wazuh-control: No such file or directory",
15:10:14              "    solaris10_gcc9: /var/ossec*: No such file or directory",
15:10:14              "    solaris10_gcc9: UX: userdel: ERROR: wazuh does not exist.",
15:10:14              "    solaris10_gcc9: UX: groupdel: ERROR: wazuh does not exist."
```
```
JENKINS_REFERENCE master
SOURCE_REFERENCE b9ccc72f0c63f23439f39a86fba95bbfbe008642
REVISION 0.commitb9ccc72
PACKAGES_REFERENCE master
TASK_DEFINITION_SUFFIX _gcc9
```
https://ci.wazuh.info/job/Packages_builder_solaris/20913/

**Comment by rauldpm** [comment] 2022-08-22 14:18
### Update report

After relaunching the build it has been observed that the package has been generated correctly, we must investigate the cause of this intermittent failure in the generation of the package and find a solution.

**Comment by lchico** [comment] 2024-01-29 22:07
# Update

Taking into account that this issue dates back a long time, I just checked the current state of the master. The test involved opening a branch from master with a very long branch name, something that we suspect could be the reason for the failure, and running the package builder for Solaris.
I successfully built the package.

![image](https://github.com/wazuh/wazuh-packages/assets/21695385/7f0fd38d-0596-4861-90b6-6b13ec7b043e)

Link to build the package: https://ci.wazuh.info/job/Packages_builder_solaris/31357/

**Comment by MarcelKemp** [comment] 2024-01-30 11:37
After verifying that there are no problems in the pipeline, as the last executions have been successful. 
And also, check that there are no problems with the length of the branches (which was an assumption of the possible error).

I proceed to close the issue, as the issue is very old and is currently fixed.

**Closed by MarcelKemp** 2024-01-30 11:37 UTC
Labels: level/task, type/bug
