### ISSUE TITLE
Check ports function could avoid the installation although none of the required ports are used

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1857] opened 2022-09-22 16:06 UTC
We noticed in a fresh Ubuntu 22.04 deployment a case where the unattended installer doesn't complete the installation. 

## Detected problem
The installation assistant output shows the following message:
`Port 443 is being used by another process. Please, check it before installing Wazuh.`

## Rationale
The command used to detect if a port is used or not contains a `grep`. If randomly, a PID of a process with opened port (detected by `ss` or `lsof` have the same PID of one required port, it will be detected. It's not too common, but it's possible. 

```
root@ip-172-31-94-168:/home/ubuntu# ss -lntup | grep 443
udp   UNCONN 0      0           127.0.0.53%lo:53        0.0.0.0:*    users:(("systemd-resolve",pid=443,fd=13))
tcp   LISTEN 0      4096        127.0.0.53%lo:53        0.0.0.0:*    users:(("systemd-resolve",pid=443,fd=14))
```

## Solution
We need to find an `ss` or `lsof` option/flag that filters only by used port, avoiding the `grep` use.

**Comment by verdx** [comment] 2022-11-04 14:26
Right now, function `check_ports()` has two possible methods to check the ports used.

1. If `ss` is installed, it uses the command `ss -tulpn | grep -q $PORT`. This method:
    - Gives us all open ports:
    ```
    ```
    - But is susceptible to the error explained in this issue as `grep` could retrieve ports that contain the one looked for
2. If `ss` is not installed but `lsof` is, it uses the command `lsof -i:$PORT`. This method:
    - Gives us all open ports(when called using `sudo`, as in the script)
    ```
    ```
    - Is not susceptible to the error explained in this issue, as it doesn't use an external tool to look for the port.

Some options to solve the problem would be:
- Improve the regex to use a better `grep`, using, for example, `grep -q '[^0-9]$PORT[^0-9]'`, although this would mean changing the architecture of the function

- Remove the option to use `ss` to get the open port with or without an alternative:
    - Make `lsof` a dependency for the Installation Assistant
    - Add another option, for example, `netcat -zv localhost $PORT`
    - Do the check only if `lsof` is installed

**Comment by verdx** [comment] 2022-11-18 09:51
After reviewing the `man` documentation of command `ss`, there is a way to check a specific port, by using the filter functionality, specifically the source port filter, the command must include `sport $PORT`, as seen in this run:
```
[verdx@verdx-smol ~]$ ss -tulpn
Netid         State           Recv-Q          Send-Q                   Local Address:Port                   Peer Address:Port         Process         
tcp           LISTEN          0               128                          127.0.0.1:631                         0.0.0.0:*                            
tcp           LISTEN          0               128                              [::1]:631                            [::]:*                            
[verdx@verdx-smol ~]$ ss -tulpn sport 22
Netid          State          Recv-Q          Send-Q                   Local Address:Port                   Peer Address:Port         Process         
[verdx@verdx-smol ~]$ ss -tulpn sport 631
Netid         State           Recv-Q          Send-Q                   Local Address:Port                   Peer Address:Port         Process         
tcp           LISTEN          0               128                          127.0.0.1:631                         0.0.0.0:*                            
tcp           LISTEN          0               128                              [::1]:631                            [::]:*                            
[verdx@verdx-smol ~]$ ss -tulpn sport 63
Netid          State          Recv-Q          Send-Q                   Local Address:Port                   Peer Address:Port         Process         
[verdx@verdx-smol ~]$ 
```
The solution is simpler than previously proposed, the `grep` command should be changed for this internal filter. Command
```
ss -tulpn | grep -q $PORT
```
should be substituted for:
```
ss -tulpn sport $PORT
```

**Comment by davidcr01** [comment] 2022-11-21 13:01
## Update report

### Research

- I have been reading the issue and following the research done by @verdx.
- I tried an example using the `sport`  option:

<details>
<summary>Example</summary>

- Display ports with `ss -lntu`. I pick port 5455 for this example.
![image](https://user-images.githubusercontent.com/72193239/203060112-63893a4a-4036-4bf3-ad4a-8e7533896038.png)

- Display ports as before, but filtering with `grep` option.
![image](https://user-images.githubusercontent.com/72193239/203060404-eea087a5-a97c-4836-ac92-3983fd254b08.png)

- Display ports using `sport` option, and shows the same output as the previous step, so it works fine.
![image](https://user-images.githubusercontent.com/72193239/203060671-7126be54-788d-4209-ba0f-fd723b05bbef.png)

- Use `sport` option with the wrong port (535 instead of 5355) and no output is displayed, so it works fine.
![image](https://user-images.githubusercontent.com/72193239/203061042-76cf01dc-5d67-420d-a32a-10b5588190cf.png)

With this example, it is shown that `grep` problem would be solved with this alternative.

</details>
        
### Next steps

- Change the `checks_ports()` function removing the `grep` option. 
- Push changes to the branch of the issue: `1857-check-ports-change-grep`
- Try to install Wazuh with `unattended_installer` in AWS Linux 2, RHEL, CentOS, and Ubuntu system versions and check the installations finish correctly.

**Comment by davidcr01** [comment] 2022-11-22 17:22
This is the PR that would solve this issue: https://github.com/wazuh/wazuh-packages/pull/1942
Now, I proceed to the testing part:

## Test definitions

Because of the difficulty of knowing or assigning a PID to a specific process, I proceed to do 3 tests:

- **Test 1**: without modifying the code of the PR, I'm going to start a service with `sudo python3 -m http.server 443`, and ensure that `wazuh-install.sh` fails. This is the expected behavior.

- **Test 2**: without modifying the code of the PR and without starting a service, the `wazuh-install.sh` script would complete the installation as expected. This is the expected behavior.

- **Test 3**: I modify the `wazuh-install.sh` script adding a code line that runs a script or background process in order to store its PID in a variable. After this, I change the defined port used by `wazuh-install.sh` by the stored PID. With this, I'm forcing the port number to a PID. With this modification, `wazuh-install.sh` script should complete the installation as expected, keeping in mind that `sport` option search for used ports and not PIDs.

**Comment by davidcr01** [comment] 2022-11-23 08:39
## Update Report

After discussing how to abord this problem (thanks @rauldpm and @verdx for the help) I finally created a process with a PID that contains "443". 
Here is the script I used to create a process with a specific PID: https://efiop-notes.blogspot.com/2014/06/how-to-set-pid-using-nslastpid.html

With this, the **Definition tests** defined in the previous update report will be the same except the **Test 3**

- **Test 3**: I create the process with a PID that contains 443 (I could not create it with PID=443 for unknown reasons), for example, 10443, and this process will launch an HTTP server with python (`python -m HTTPSimpleServer 1234`). If you have Python 3.x use `python -m http. server 1234`, where 1234 is the port you want. With this example, we got a very similar situation described in the issue. The `wazuh-install.sh` script should complete the installation as expected, keeping in mind that `sport` option search for used ports and not PIDs.:

![image](https://user-images.githubusercontent.com/72193239/203501696-bfb34907-549a-4117-8458-3b05f5fe746f.png)

We have an HTTP server launched with python with PID 10443 using port 1234.
Besides, this screenshot shows that the unattended installer could fail with a port that contains the desired port. In this case `grep 443` command would match 10443.

**Comment by davidcr01** [comment] 2022-11-23 11:54
## Update report

Unfortunately, I noticed that the `sport` option was available in some versions of the `ss` command.

After discussing the approach with the team, we thought that the best option was to delete the `ss` command of the `checks_port()` function and use `lsof` as the only port command checker, as it is not susceptible to errors, and make `lsof` a dependency of the unattended installer.

## Tests

- [ ] Amazon Linux 2
- [ ] RHEL 7
- [ ] RHEL 8
- [ ] RHEL 9
- [ ] CentOS 7
- [ ] CentOS 8
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04

**Comment by davidcr01** [comment] 2022-11-24 19:17
## Update report

:heavy_check_mark: Tests for Ubuntu 16.04, 18.04, 20.04 and CentOS 7 passed.

:warning: I could not try the test for Ubuntu 16.04 on my local machine, using Vagrant with 3GB of RAM and 2 cores of CPU. During the installation, the wazuh-manager service could not start and the timeout produced a failed installation. Nevertheless, the test passed in an AWS machine with 8GB RAM and 4 cores of CPU.

:heavy_check_mark: Finally, the test passed locally by removing and re-adding the Ubuntu 16 vagrant box.

**Comment by davidcr01** [comment] 2022-11-28 07:59
## Update report

:heavy_check_mark: Tests for Ubuntu CentOS 8 passed.

**Comment by alberpilot** [comment] 2022-11-30 09:25
Tests fail due to https://github.com/wazuh/wazuh-packages/issues/1954. This issue goes to On Hold until problem resolution.

**Comment by davidcr01** [comment] 2022-12-15 17:16
This issue goes to On Hold until https://github.com/wazuh/wazuh-packages/issues/1984 is closed and checks pass correctly.

**Comment by davidcr01** [comment] 2022-12-22 19:03
## Update Report

Currently working on the GitHub Action workflow. 

https://github.com/wazuh/wazuh-packages/blob/1850-wazuh-indexer-preserve-config-files-upon-upgrade-master/.github/workflows/test-indexer.yml

https://github.com/wazuh/wazuh-packages/blob/1850-wazuh-indexer-preserve-config-files-upon-upgrade-master/.github/actions/upgrade-indexer/test-debian.sh

**Comment by davidcr01** [comment] 2022-12-27 11:28
This issue goes to Blocked until https://github.com/wazuh/wazuh/issues/15802 is closed and merged.

**Closed** 2023-01-09 16:12 UTC
Labels: type: bug, component: installation-assistant
