### ISSUE TITLE
wazuh-packages v4.3.10 build debian amd64 docker image failed.

### ISSUE THREAD

**Issue by LubinLew** [wazuh/wazuh-packages#2097] opened 2023-02-15 03:18 UTC
### cmds
```bash
git clone -b v4.3.10 --depth 1 https://github.com/wazuh/wazuh-packages.git
cd wazuh-packages/debs
./generate_debian_package.sh -b v4.3.10 -t agent -a x86_64 -r 1  --packages-branch v4.3.10
```

### errors
```bash
Step 1/[12]: FROM debian:7
7: Pulling from library/debian
2b15b7abe8b3: Pulling fs layer
2b15b7abe8b3: Verifying Checksum
2b15b7abe8b3: Download complete
2b15b7abe8b3: Pull complete
Digest: sha256:2259b099d947443e44bbd1c94967c785361af8fd22df48a08a3942e2d5630849
Status: Downloaded newer image for debian:7
 ---> 10fcec6d95c4
Step 2/12 : ENV DEBIAN_FRONTEND noninteractive
 ---> Running in fbd149b98acf
Removing intermediate container fbd149b98acf
 ---> ba7d705920ba
Step 3/12 : RUN echo "deb http://archive.debian.org/debian/ wheezy contrib main non-free" > /etc/apt/sources.list &&     echo "deb-src http://archive.debian.org/debian/ wheezy contrib main non-free" >> /etc/apt/sources.list &&     apt-get update && apt-get install -y apt-utils &&     apt-get install -y --force-yes     curl gcc make sudo wget expect gnupg perl-base=5.14.2-21+deb7u3 perl     libc-bin=2.[13](https://github.com/LubinLew/container-mirrors/actions/runs/4180213892/jobs/7240976121#step:2:14)-38+deb7u10 libc6=2.13-38+deb7u10 libc6-dev build-essential     cdbs devscripts equivs automake autoconf libtool libaudit-dev selinux-basics     libdb5.1=5.1.29-5 libdb5.1-dev libssl1.0.0=1.0.1e-2+deb7u20 procps gawk libsigsegv2
 ---> Running in fb2c88ef3cc4
Get:1 http://archive.debian.org wheezy Release.gpg [2373 B]
Get:2 http://archive.debian.org wheezy Release [191 kB]
Ign http://archive.debian.org wheezy Release
Get:3 http://archive.debian.org wheezy/contrib Sources [55.8 kB]
Get:4 http://archive.debian.org wheezy/main Sources [7533 kB]
Get:5 http://archive.debian.org wheezy/non-free Sources [112 kB]
Get:6 http://archive.debian.org wheezy/contrib amd64 Packages [50.5 kB]
Get:7 http://archive.debian.org wheezy/main amd64 Packages [7634 kB]
Get:8 http://archive.debian.org wheezy/non-free amd64 Packages [100 kB]
Fetched 15.7 MB in 2s (6731 kB/s)
Reading package lists...
W: GPG error: http://archive.debian.org wheezy Release: The following signatures were invalid: KEYEXPIRED 1587841717 KEYEXPIRED 1668891673 KEYEXPIRED 1557241909
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  libapt-inst1.5
The following NEW packages will be installed:
  apt-utils libapt-inst1.5
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 545 kB of archives.
After this operation, 2049 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  libapt-inst1.5 apt-utils
E: There are problems and -y was used without --force-yes
The command '/bin/sh -c echo "deb http://archive.debian.org/debian/ wheezy contrib main non-free" > /etc/apt/sources.list &&     echo "deb-src http://archive.debian.org/debian/ wheezy contrib main non-free" >> /etc/apt/sources.list &&     apt-get update && apt-get install -y apt-utils &&     apt-get install -y --force-yes     curl gcc make sudo wget expect gnupg perl-base=5.[14](https://github.com/LubinLew/container-mirrors/actions/runs/4180213892/jobs/7240976121#step:2:15).2-21+deb7u3 perl     libc-bin=2.13-38+deb7u10 libc6=2.13-38+deb7u10 libc6-dev build-essential     cdbs devscripts equivs automake autoconf libtool libaudit-dev selinux-basics     libdb5.1=5.1.29-5 libdb5.1-dev libssl1.0.0=1.0.1e-2+deb7u[20](https://github.com/LubinLew/container-mirrors/actions/runs/4180213892/jobs/7240976121#step:2:21) procps gawk libsigsegv2' returned a non-zero code: 100
```

**Comment by tsarquis88** [comment] 2023-03-28 10:57
Same problem here on `Pop_OS! 22.04` distro. Tested on branch `v4.3.8`.

### Steps to reproduce
```
git clone https://github.com/wazuh/wazuh-packages
cd wazuh-packages/debs
git checkout -v4.3.8
docker build file=Debian/amd64/Dockerfile .
```

### Workaround

I've workarounded (fixed?) this by adding `--force-yes` on `apt-get install -y apt-utils` and `apt-get build-dep python3.2 -y` in `Debian/amd64/` dockerfile.

**Comment by DFolchA** [comment] 2023-03-28 11:23
Hello,

Thank you for reporting this problem. The solution proposed by @tsarquis88 is correct and was added to 4.4.0 in this PR: 
https://github.com/wazuh/wazuh-packages/pull/2098

I am closing the issue because it is a duplicate of this one:
https://github.com/wazuh/wazuh-packages/issues/1964

**Closed** 2023-03-28 11:24 UTC
