### ISSUE TITLE
Certificates renamed when upgrading to 4.4.0

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-packages#2151] opened 2023-04-05 07:51 UTC
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.8 -> 4.4.0 | Manager | Upgrade | Ubuntu 20 |

**Note:** I'm not sure which repository this issue belongs to. Please transfer if necessary.

## Description

I found a problem twice while upgrading from Wazuh v4.3.8 to v4.4.0. I did not test it for different initial versions.

When upgrading Wazuh following the steps listed here:
- [Wazuh central components](https://documentation.wazuh.com/current/upgrade-guide/upgrading-central-components.html)

Neither the indexer nor the dashboard could start successfully after completing the process. After doing some research, it turns out the name of the certificates was incorrect. I had not renamed them manually. Also, in 4.3.8 everything was working correctly. The indexer was looking for the following files:
- `/etc/wazuh-indexer/certs/indexer.pem`
- `/etc/wazuh-indexer/certs/indexer-key.pem`

But in the certs folder, the existing files had this name:
- `/etc/wazuh-indexer/certs/wazuh-indexer.pem`
- `/etc/wazuh-indexer/certs/wazuh-indexer-key.pem`

The same was happening for the dashboard. In case it is related in any way, while upgrading, I pressed `Y` for each of the messages like this:
```
configuration file '/etc/wazuh-indexer/opensearch.yml'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** opensearch.yml (Y/I/N/O/D/Z) [default=N] ? Y
```

Maybe there should be a note in the documentation about the correct input when that happens.

**Comment by rauldpm** [comment] 2023-04-14 17:01
After checking the behavior, i were able to verify that an upgrade from 4.3.10 (installed via wazuh-install.sh -a) to 4.4.1, does not alter the name of the certificates in the configuration file and these are kept as wazuh-indexer.

The case raised in this problem happens because the origin certificates have a different name (either because the installation media at the time of installation used another nomenclature or because the user set a different name), as mentioned in the system message

```
==> Modified (by you or by a script) since installation.
  ==> Package distributor has shipped an updated version.
    What would you like to do about it? Your options are:
     Y or I : install the package maintainer's version
     N or O : keep your currently-installed version
```

- If Y is pressed, it installs the configuration of the new package (overrides).
- If N is pressed, it maintains the old configuration (do not overrides).

Here we have two initial options:

1. Add a note in the documentation indicating that the name of the certificates must be checked in the configuration after the upgrade (the user shouldn't really be aware of this but it should be the responsibility of the package)
2. Add what is necessary to the SPECS file so that the opensearch.yml and opensearch-dashboard.yml files are modified with the name of the certificates found in the certs folder after installing the new configuration file (post-install stage)

**Comment by DFolchA** [comment] 2023-04-18 16:29
## Update

We have been investigating the cause of the message, we found that according to the documentation all the files installed under `/etc` are considered configuration files by default, and will prompt the message when upgrading the package if they were modified by the user.
*Source:* https://www.debian.org/doc/manuals/maint-guide/dother.en.html#conffiles

We have also replicated this behavior in OpenSearch packages:
```
root@ubuntu18LTS:/home/vagrant# apt install ./opensearch-2.6.0-linux-x64.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'opensearch' instead of './opensearch-2.6.0-linux-x64.deb'
The following packages will be upgraded:
  opensearch
1 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.
Need to get 0 B/744 MB of archives.
After this operation, 15.7 MB disk space will be freed.
Get:1 /home/vagrant/opensearch-2.6.0-linux-x64.deb opensearch amd64 2.6.0 [744 MB]
(Reading database ... 97702 files and directories currently installed.)
Preparing to unpack .../opensearch-2.6.0-linux-x64.deb ...
Running OpenSearch Pre-Removal Script
Running OpenSearch Pre-Installation Script
Unpacking opensearch (2.6.0) over (2.5.0) ...
Setting up opensearch (2.6.0) ...

Configuration file '/etc/opensearch/opensearch.yml'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** opensearch.yml (Y/I/N/O/D/Z) [default=N] ? y
Installing new version of config file /etc/opensearch/opensearch.yml ...
Running OpenSearch Post-Installation Script
### NOT starting on installation, please execute the following statements to configure opensearch service to start automatically using syste
md
 sudo systemctl daemon-reload
 sudo systemctl enable opensearch.service
### You can start opensearch service by executing
 sudo systemctl start opensearch.service
### Create opensearch demo certificates in /etc/opensearch/
 See demo certs creation log in /var/log/opensearch/install_demo_configuration.log
Processing triggers for libc-bin (2.27-3ubuntu1.6) ...
Processing triggers for systemd (237-3ubuntu10.57) ...
Processing triggers for ureadahead (0.100.0-21) ...
```

After discussing with the team we determined that we have various options:
1. Consider this the expected behavior as it is intended by the package manager and the message indicates that the previous configuration will be replaced when pressing `Y`.
2. Remove the file from the `conffiles` and manage it during pre-install and post-install steps so the previous config file always remains after an upgrade. When doing the user may skip  key changes in the default configuration and we may need to set the same treatment for all files in `/etc/wazuh-indexer`.

Finally, we have decided to go with the first option and leave the packages as it is.

**Closed** 2023-04-20 00:09 UTC
Labels: upgrade, wazuh-indexer, wazuh-dashboard, type/bug
