### ISSUE TITLE
Unable to install wazuh-manager 2.0 in Ubuntu 16.04.2 LTS (Xenial Xerus)

### ISSUE THREAD

**Issue by michaelhidalgo** [wazuh/wazuh-packages#25] opened 2018-07-11 14:54 UTC
Hi folks, we are trying to install Wazuh manager 2 from the sources following this guide https://documentation.wazuh.com/2.0/installation-guide/installing-wazuh-server/wazuh_server_deb.html .

The target operating system is Ubuntu 16.04.2 LTS (Xenial Xerus) codename xenial.

However, after adding the GPG-KEY-WAZUH, we get the error : 
Some packages could not be authenticated when installing wazuh Manager.

Please see below screenshot

![screen shot 2018-07-11 at 7 55 41 am](https://user-images.githubusercontent.com/1732035/42580441-c6ffa330-84e7-11e8-9632-dbdef5026d54.png)

I wonder if you have seen this issue before and if there is any recommendation on how to fix it.

**Comment by michaelhidalgo** [comment] 2018-07-13 04:05
Hi folks, any update on this?

**Comment by BraulioV** [comment] 2018-07-13 06:51
Hi @michaelhidalgo,

sorry for the late response. I was trying to reproduce your error but I couldn't. What I would recommend is to remove the GPG key, the repository and try again.

To remove the key you can do the following:
```
# sudo apt-key list
```

It will show you something like this:
```
# sudo apt-key list
/etc/apt/trusted.gpg
--------------------
pub   4096R/29111145 2016-08-01 [expires: 2019-08-01]
uid                  Wazuh.com (Wazuh Signing Key) <support@wazuh.com>
sub   4096R/664FAB32 2016-08-01 [expires: 2019-08-01]
```

Then, remove the key by using `sudo apt-key del <keyid>`. In this case:

```
# sudo apt-key del 29111145
```

And then, add the key and try to install the package. Make sure that `apt-transport-https` is installed.

In addition, I recommend you to upgrade to the latest Wazuh version.

Thank you for your patience and if you have any trouble, please, don't hesitate to write again.

Regards,
Braulio.

**Comment by BraulioV** [comment] 2018-08-17 17:28
Hi,

it has been two months since the last response, so I proceed to close this issue. If you have any questions feel free to reopen it.

Regards,
Braulio.

**Closed by BraulioV** 2018-08-17 17:28 UTC

**Comment by michaelhidalgo** [comment] 2018-08-21 02:35
+1
