### ISSUE TITLE
APT upgrade to wazuh-agent 4.8.0 not working

### ISSUE THREAD

**Issue by Lefuneste83** [wazuh/wazuh-packages#2707] opened 2023-12-19 16:41 UTC
Latest version of wazuh-agent 4.8.0 is published as an available update on 

deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main

But when doing apt upgrade I get 

Err :1 https://packages.wazuh.com/4.x/apt stable/main amd64 wazuh-agent amd64 4.8.0-python310
  404  Not Found [IP : 18.244.28.87 443]
E: Impossible de récupérer https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.8.0-python310_amd64.deb  404  Not Found [IP : 18.244.28.87 443]
E: Impossible de récupérer certaines archives, peut-être devrez-vous lancer apt-get update ou essayer avec --fix-missing ?

**Comment by rauldpm** [comment] 2023-12-19 20:13
Hello, we are aware of the existence of this problem, and we have already fixed it, please run an `apt get update` command and check again, you might have to to manually clear `/var/lib/apt/lists`

Regards

**Comment by Lefuneste83** [comment] 2023-12-19 21:28
The broken repository actually broke connectivity on my already deployed clients so I had to manually roll back to 4.7.0 version to restore connectivity.

The repository appears to be fixed as the current published version is back to 4.7.0 once I purged the previous cache with : 

`rm /var/lib/apt/lists/*wazuh*`

Now apt update does not offer to upgrade wazuh-agent anymore.

**Comment by rauldpm** [comment] 2023-12-19 21:32
I'm glad you were able to solve it, if the problem is solved please close the issue, if you have any other problem don't hesitate to contact us!

**Closed** 2023-12-19 23:37 UTC
