### ISSUE TITLE
Windows agent fails to upgrade and leaves some registry entries that prevent a clean installation

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh-packages#2239] opened 2023-06-21 21:23 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.4.4-1| .msi installation | Agent | Packages | Windows |

### Description

It was reported by a community user (see the Slack [thread](https://wazuh.slack.com/archives/C0A933R8E/p1686945993530609)) that after trying an upgrade from version `4.3.10` to `4.4.4`, the Windows agent upgrade failed and no clean installations were possible in the affected systems.

The installation seems successful, but no files are copied at all. See the .msi installation logs
[wazuh-install-log.txt](https://github.com/wazuh/wazuh-packages/files/11826258/wazuh-install-log.txt)

The only way that the user was able to install the product was to manually delete the following registry entry

```

HKEY_CLASSES_ROOT\Installer\Products\2CCD14952D327D94E99EA35590E81BD9
```

It's required to further investigate this issue and find the root cause.

The following issues might be related:

https://github.com/wazuh/wazuh/issues/15196
https://github.com/wazuh/wazuh/issues/17046
https://github.com/wazuh/wazuh/issues/17047
https://github.com/wazuh/wazuh/issues/17141

**Comment by pereyra-m** [comment] 2023-06-22 18:43
## Update

I'm adding some extra information that the user shared:
- The issue happened in an environment with 80 Windows agents

> All windows, but windows 10, windows 11, windows server 2016 e 2016 datacenter , windows server 2019 datacenter, Microsoft Hyper-V Server 2019

- Some of them have a non-English locale

> Windows servers are in English, but Windows desktops are in Portuguese, but both had the same problem

- This is a capture from the registry

![image (20)](https://github.com/wazuh/wazuh-packages/assets/65046601/a650b6c6-69a0-4028-85ba-6bc1c319e7e3)

**Comment by pereyra-m** [comment] 2023-06-28 13:27
## Update

A similar situation happened in another environment.
[This](https://wazuh.slack.com/archives/C0A933R8E/p1687955173498569) Slack user reported that the upgrade from **4.4.0** to **4.4.4** failed. But he was able to perform a clean installation.
OS:  Windows 2016 Datacenter (some others in the same environment worked fine)
Language: English US

Here we have the corresponding logs

**upgrade.log**

<details><summary>Details</summary>
<p>

```
2023-06-28 07:05:55Z - Current version: v4.4.0.
2023-06-28 07:05:55Z - Generating backup.
2023-06-28 07:05:55Z - Backing up Wazuh home files.
2023-06-28 07:05:56Z - Searching Wazuh-Agent cached MSI through the registry.
2023-06-28 07:05:56Z - Backing up Wazuh-Agent cached MSI: "C:\windows\Installer\c6673dad.msi".
2023-06-28 07:05:57Z - Trying to stop Wazuh service.
2023-06-28 07:05:59Z - Starting upgrade processs.
2023-06-28 07:06:02Z - Restarting Wazuh-Agent service.
2023-06-28 07:06:02Z - Installation finished.
2023-06-28 07:06:02Z - Process ID: 1840.
2023-06-28 07:06:22Z - Reading status file: .
2023-06-28 07:06:22Z - Upgrade failed: Restoring former installation.
2023-06-28 07:06:22Z - Trying to stop Wazuh service.
2023-06-28 07:06:24Z - Trying to stop Wazuh service again. Remaining attempts: 5.
2023-06-28 07:06:26Z - Trying to stop Wazuh service again. Remaining attempts: 4.
2023-06-28 07:06:28Z - Trying to stop Wazuh service again. Remaining attempts: 3.
2023-06-28 07:06:30Z - Trying to stop Wazuh service again. Remaining attempts: 2.
2023-06-28 07:06:32Z - Trying to stop Wazuh service again. Remaining attempts: 1.
2023-06-28 07:06:34Z - Killing process.
2023-06-28 07:06:45Z - Performing the Wazuh-Agent uninstall using: "MsiExec.exe /X{6A91A325-FA7E-40E9-BB54-FFCD29500849} /quiet".
2023-06-28 07:06:54Z - Excecuting former Wazuh-Agent MSI: ".\backup\c6673dad.msi".
2023-06-28 07:06:55Z - Waiting for the installation to end.
2023-06-28 07:06:58Z - Restoring former Wazuh-Agent home files.
2023-06-28 07:06:58Z - Current version: v4.4.0.
2023-06-28 07:06:58Z - Installing Wazuh service.
2023-06-28 07:06:58Z - Starting Wazuh-Agent service.
```

</p>
</details> 

**ossec.log**

<details><summary>Details</summary>
<p>

```
2023/06/28 00:00:10 wazuh-agent: INFO: Starting new log after rotation.
2023/06/28 00:01:07 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2023/06/28 00:01:12 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2023/06/28 01:01:13 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2023/06/28 01:01:19 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2023/06/28 02:01:20 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2023/06/28 02:01:25 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2023/06/28 02:34:56 sca: INFO: Starting Security Configuration Assessment scan.
2023/06/28 02:34:56 sca: INFO: Starting evaluation of policy: 'C:\Program Files (x86)\ossec-agent\ruleset\sca\cis_win2016.yml'
2023/06/28 02:34:59 sca: INFO: Evaluation finished for policy 'C:\Program Files (x86)\ossec-agent\ruleset\sca\cis_win2016.yml'
2023/06/28 02:34:59 sca: INFO: Security Configuration Assessment scan finished. Duration: 3 seconds.
2023/06/28 02:36:02 wazuh-agent: ERROR: Could not EvtFormatMessage() to determine buffer size with flags (1) which returned (15027)
2023/06/28 02:36:02 wazuh-agent: ERROR: Could not get message for (Application)
2023/06/28 02:36:58 rootcheck: INFO: Starting rootcheck scan.
2023/06/28 02:37:03 rootcheck: INFO: Ending rootcheck scan.
2023/06/28 02:41:00 wazuh-agent: INFO: (6008): File integrity monitoring scan started.
2023/06/28 02:41:18 wazuh-agent: INFO: (6009): File integrity monitoring scan ended.
2023/06/28 03:01:26 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2023/06/28 03:01:32 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2023/06/28 04:01:33 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2023/06/28 04:01:39 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2023/06/28 05:01:40 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2023/06/28 05:01:46 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2023/06/28 06:01:47 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2023/06/28 06:01:52 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2023/06/28 06:44:45 wazuh-agent: ERROR: (1137): Lost connection with manager. Setting lock.
2023/06/28 06:44:45 wazuh-agent: INFO: Closing connection to server ([X.X.X.X]:1514/tcp).
2023/06/28 06:44:45 wazuh-agent: INFO: Trying to connect to server ([X.X.X.X]:1514/tcp).
2023/06/28 06:44:46 wazuh-agent: WARNING: Process locked due to agent is offline. Waiting for connection...
2023/06/28 06:44:46 wazuh-agent: ERROR: (1216): Unable to connect to '[X.X.X.X]:1514/tcp': 'No connection could be made because the target machine actively refused it.'.
2023/06/28 06:44:56 wazuh-agent: INFO: Trying to connect to server ([X.X.X.X]:1514/tcp).
2023/06/28 06:44:57 wazuh-agent: ERROR: (1216): Unable to connect to '[X.X.X.X]:1514/tcp': 'No connection could be made because the target machine actively refused it.'.
2023/06/28 06:45:07 wazuh-agent: INFO: Trying to connect to server ([X.X.X.X]:1514/tcp).
2023/06/28 06:45:08 wazuh-agent: ERROR: (1216): Unable to connect to '[X.X.X.X]:1514/tcp': 'No connection could be made because the target machine actively refused it.'.
2023/06/28 06:45:18 wazuh-agent: INFO: Trying to connect to server ([X.X.X.X]:1514/tcp).
2023/06/28 06:45:19 wazuh-agent: ERROR: (1216): Unable to connect to '[X.X.X.X]:1514/tcp': 'No connection could be made because the target machine actively refused it.'.
2023/06/28 06:45:29 wazuh-agent: INFO: Trying to connect to server ([X.X.X.X]:1514/tcp).
2023/06/28 06:45:30 wazuh-agent: ERROR: (1216): Unable to connect to '[X.X.X.X]:1514/tcp': 'No connection could be made because the target machine actively refused it.'.
2023/06/28 06:45:30 wazuh-agent: INFO: Requesting a key from server: X.X.X.X
2023/06/28 06:45:31 wazuh-agent: ERROR: (1208): Unable to connect to enrollment service at '[X.X.X.X]:1515'
2023/06/28 06:45:41 wazuh-agent: WARNING: (4101): Waiting for server reply (not started). Tried: 'X.X.X.X'.
2023/06/28 06:45:41 wazuh-agent: WARNING: Unable to connect to any server.
2023/06/28 06:45:41 wazuh-agent: INFO: Trying to connect to server ([X.X.X.X]:1514/tcp).
2023/06/28 06:45:42 wazuh-agent: ERROR: (1216): Unable to connect to '[X.X.X.X]:1514/tcp': 'No connection could be made because the target machine actively refused it.'.
2023/06/28 06:45:47 wazuh-agent: WARNING: Process locked due to agent is offline. Waiting for connection...
2023/06/28 06:45:52 wazuh-agent: INFO: Trying to connect to server ([X.X.X.X]:1514/tcp).
2023/06/28 06:45:53 wazuh-agent: ERROR: (1216): Unable to connect to '[X.X.X.X]:1514/tcp': 'No connection could be made because the target machine actively refused it.'.
2023/06/28 06:46:03 wazuh-agent: INFO: Trying to connect to server ([X.X.X.X]:1514/tcp).
2023/06/28 06:46:04 wazuh-agent: ERROR: (1216): Unable to connect to '[X.X.X.X]:1514/tcp': 'No connection could be made because the target machine actively refused it.'.
2023/06/28 06:46:14 wazuh-agent: INFO: Trying to connect to server ([X.X.X.X]:1514/tcp).
2023/06/28 06:46:15 wazuh-agent: ERROR: (1216): Unable to connect to '[X.X.X.X]:1514/tcp': 'No connection could be made because the target machine actively refused it.'.
2023/06/28 06:46:25 wazuh-agent: INFO: Trying to connect to server ([X.X.X.X]:1514/tcp).
2023/06/28 06:46:26 wazuh-agent: ERROR: (1216): Unable to connect to '[X.X.X.X]:1514/tcp': 'No connection could be made because the target machine actively refused it.'.
2023/06/28 06:46:26 wazuh-agent: INFO: Requesting a key from server: X.X.X.X
2023/06/28 06:46:26 wazuh-agent: INFO: No authentication password provided
2023/06/28 06:46:26 wazuh-agent: INFO: Using agent name as: AGENTNAME
2023/06/28 06:46:26 wazuh-agent: INFO: Waiting for server reply
2023/06/28 06:46:26 wazuh-agent: ERROR: Duplicate agent name: AGENTNAME (from manager)
2023/06/28 06:46:26 wazuh-agent: ERROR: Unable to add agent (from manager)
2023/06/28 06:46:36 wazuh-agent: WARNING: (4101): Waiting for server reply (not started). Tried: 'X.X.X.X'.
2023/06/28 06:46:36 wazuh-agent: WARNING: Unable to connect to any server.
2023/06/28 06:46:36 wazuh-agent: INFO: Trying to connect to server ([X.X.X.X]:1514/tcp).
2023/06/28 06:46:36 wazuh-agent: INFO: (4102): Connected to the server ([X.X.X.X]:1514/tcp).
2023/06/28 06:46:36 wazuh-agent: INFO: Server responded. Releasing lock.
2023/06/28 06:46:37 wazuh-agent: INFO: Agent is now online. Process unlocked, continuing...
2023/06/28 06:46:41 wazuh-agent: INFO: Agent is now online. Process unlocked, continuing...
2023/06/28 07:01:53 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2023/06/28 07:01:59 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2023/06/28 07:05:57 wazuh-agent: INFO: Received exit signal. Starting exit process.
2023/06/28 07:05:57 wazuh-agent: INFO: Set pending exit signal.
2023/06/28 07:05:57 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2023/06/28 07:05:57 wazuh-modulesd:syscollector: INFO: Module finished.
2023/06/28 07:05:57 wazuh-agent: INFO: Exit completed successfully.
2023/06/28 07:05:57 wazuh-agent: INFO: (1314): Shutdown received. Deleting responses.
2023/06/28 07:06:18 wazuh-agent: INFO: Using notify time: 10 and max time to reconnect: 60
2023/06/28 07:06:18 wazuh-agent: INFO: (1410): Reading authentication keys file.
2023/06/28 07:06:18 wazuh-agent: INFO: Started (pid: 1840).
2023/06/28 07:06:18 wazuh-agent: INFO: Using AES as encryption method.
2023/06/28 07:06:18 wazuh-agent: INFO: Trying to connect to server ([X.X.X.X]:1514/tcp).
2023/06/28 07:06:18 wazuh-agent: INFO: (4102): Connected to the server ([X.X.X.X]:1514/tcp).
2023/06/28 07:06:18 rootcheck: INFO: Started (pid: 1840).
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\batfile', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\cmdfile', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\comfile', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\exefile', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\piffile', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\AllFilesystemObjects', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\Directory', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\Folder', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\Protocols [x64]', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Classes\Protocols', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Policies [x64]', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Policies', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Security', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Internet Explorer [x64]', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Internet Explorer', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-modulesd:agent-upgrade: INFO: (8153): Module Agent Upgrade started.
2023/06/28 07:06:18 wazuh-modulesd:osquery: INFO: Module disabled. Exiting...
2023/06/28 07:06:18 wazuh-agent: INFO: Windows version is 6.0 or newer. (Microsoft Windows Server 2016 Datacenter [Ver: 10.0.14393.5989] - Wazuh v4.4.4).
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\KnownDLLs', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-modulesd:ciscat: INFO: Module disabled. Exiting...
2023/06/28 07:06:18 sca: INFO: Module started.
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\SecurePipeServers\winreg', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run [x64]', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (1951): Analyzing event log: 'Application'.
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnce [x64]', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 sca: INFO: Loaded policy 'C:\Program Files (x86)\ossec-agent\ruleset\sca\cis_win2016.yml'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnce', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 sca: INFO: Starting Security Configuration Assessment scan.
2023/06/28 07:06:18 wazuh-agent: INFO: (1951): Analyzing event log: 'Security'.
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnceEx', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\URL [x64]', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\URL', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies [x64]', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (1951): Analyzing event log: 'System'.
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Policies', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Windows [x64]', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (1950): Analyzing file: 'active-response\active-responses.log'.
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Windows', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon [x64]', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\Winlogon', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Active Setup\Installed Components [x64]', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6002): Monitoring registry entry: 'HKEY_LOCAL_MACHINE\Software\Microsoft\Active Setup\Installed Components', with options 'size | permissions | owner | group | mtime | hash_md5 | hash_sha1 | hash_sha256'
2023/06/28 07:06:18 wazuh-agent: INFO: (6003): Monitoring path: 'c:\programdata\microsoft\windows\start menu\programs\startup', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | realtime'.
2023/06/28 07:06:18 wazuh-agent: INFO: (6003): Monitoring path: 'c:\windows', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | scheduled'.
2023/06/28 07:06:18 wazuh-agent: INFO: (6003): Monitoring path: 'c:\windows\sysnative', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | scheduled'.
2023/06/28 07:06:18 wazuh-agent: INFO: (6003): Monitoring path: 'c:\windows\sysnative\drivers\etc', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | scheduled'.
2023/06/28 07:06:18 wazuh-agent: INFO: (6003): Monitoring path: 'c:\windows\sysnative\wbem', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | scheduled'.
2023/06/28 07:06:18 wazuh-agent: INFO: (6003): Monitoring path: 'c:\windows\sysnative\windowspowershell\v1.0', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | scheduled'.
2023/06/28 07:06:18 wazuh-agent: INFO: (6003): Monitoring path: 'c:\windows\system32', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | scheduled'.
2023/06/28 07:06:18 wazuh-agent: INFO: (6003): Monitoring path: 'c:\windows\system32\drivers\etc', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | scheduled'.
2023/06/28 07:06:18 wazuh-agent: INFO: (6003): Monitoring path: 'c:\windows\system32\wbem', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | scheduled'.
2023/06/28 07:06:18 wazuh-agent: INFO: (6003): Monitoring path: 'c:\windows\system32\windowspowershell\v1.0', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | attributes | scheduled'.
2023/06/28 07:06:18 wazuh-agent: INFO: (6206): Ignore 'file' entry 'c:\programdata\microsoft\windows\start menu\programs\startup\desktop.ini'
2023/06/28 07:06:18 wazuh-agent: INFO: (6207): Ignore 'file' sregex '.log$|.htm$|.jpg$|.png$|.chm$|.pnf$|.evtx$'
2023/06/28 07:06:18 wazuh-agent: INFO: (6206): Ignore 'registry' entry 'HKEY_LOCAL_MACHINE\Security\Policy\Secrets'
2023/06/28 07:06:18 wazuh-agent: INFO: (6206): Ignore 'registry' entry 'HKEY_LOCAL_MACHINE\Security\SAM\Domains\Account\Users'
2023/06/28 07:06:18 wazuh-agent: INFO: (6206): Ignore 'registry' entry 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\MpsSvc\Parameters\AppCs'
2023/06/28 07:06:18 wazuh-agent: INFO: (6206): Ignore 'registry' entry 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\MpsSvc\Parameters\PortKeywords\DHCP'
2023/06/28 07:06:18 wazuh-agent: INFO: (6206): Ignore 'registry' entry 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\MpsSvc\Parameters\PortKeywords\IPTLSIn'
2023/06/28 07:06:18 wazuh-agent: INFO: (6206): Ignore 'registry' entry 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\MpsSvc\Parameters\PortKeywords\IPTLSOut'
2023/06/28 07:06:18 wazuh-agent: INFO: (6206): Ignore 'registry' entry 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\MpsSvc\Parameters\PortKeywords\RPC-EPMap'
2023/06/28 07:06:18 wazuh-agent: INFO: (6206): Ignore 'registry' entry 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\MpsSvc\Parameters\PortKeywords\Teredo'
2023/06/28 07:06:18 wazuh-agent: INFO: (6206): Ignore 'registry' entry 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\PolicyAgent\Parameters\Cache'
2023/06/28 07:06:18 wazuh-agent: INFO: (6206): Ignore 'registry' entry 'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\RunOnceEx'
2023/06/28 07:06:18 wazuh-agent: INFO: (6206): Ignore 'registry' entry 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\ADOVMPPackage\Final'
2023/06/28 07:06:18 wazuh-agent: INFO: (6207): Ignore 'registry' sregex '\Enum$'
2023/06/28 07:06:18 wazuh-agent: INFO: Started (pid: 1840).
2023/06/28 07:06:18 sca: INFO: Starting evaluation of policy: 'C:\Program Files (x86)\ossec-agent\ruleset\sca\cis_win2016.yml'
2023/06/28 07:06:18 wazuh-agent: INFO: (6000): Starting daemon...
2023/06/28 07:06:18 wazuh-agent: INFO: (6010): File integrity monitoring scan frequency: 43200 seconds
2023/06/28 07:06:18 wazuh-agent: INFO: (6008): File integrity monitoring scan started.
2023/06/28 07:06:21 sca: INFO: Evaluation finished for policy 'C:\Program Files (x86)\ossec-agent\ruleset\sca\cis_win2016.yml'
2023/06/28 07:06:21 sca: INFO: Security Configuration Assessment scan finished. Duration: 3 seconds.
2023/06/28 07:06:22 wazuh-agent: INFO: Received exit signal. Starting exit process.
2023/06/28 07:06:22 wazuh-agent: INFO: Set pending exit signal.
2023/06/28 07:06:22 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2023/06/28 07:06:22 wazuh-agent: INFO: Exit completed successfully.
2023/06/28 07:06:22 wazuh-agent: INFO: (1314): Shutdown received. Deleting responses.
2023/06/28 07:06:22 wazuh-agent: INFO: Found (WazuhSvc) service is not running.
2023/06/28 07:06:22 wazuh-agent: INFO: Successfully removed (WazuhSvc) from the service database.
2023/06/28 07:06:33 wazuh-modulesd:syscollector: INFO: Module started.
2023/06/28 07:06:33 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2023/06/28 07:06:33 rootcheck: INFO: Starting rootcheck scan.
2023/06/28 07:06:58 wazuh-agent: INFO: Found (WazuhSvc) service is not running.
2023/06/28 07:06:58 wazuh-agent: ERROR: Failure removing (WazuhSvc) from the service database.
2023/06/28 07:06:58 wazuh-agent: ERROR: Failure running UninstallService().
```

</p>
</details> 

Consider that the upgrade began at `2023-06-28 07:05:55Z` and failed. It rolled back to **4.4.0** but the agents reports **4.4.4** version

```
2023/06/28 07:06:18 wazuh-agent: INFO: Windows version is 6.0 or newer. (Microsoft Windows Server 2016 Datacenter [Ver: 10.0.14393.5989] - Wazuh v4.4.4).
```

Really similar to
https://github.com/wazuh/wazuh/issues/15196

**Comment by jotacarma90** [comment] 2024-05-13 17:29
# Analysis
Hello team, we have been analysing and testing this issue.
We have used newer versions as it is not worth to check behaviour of older WPKs due to the amount of fixes they have undergone.
I have tested from version 4.7.4 to 4.9.0:

- WPK success:
```
2024-05-13 08:28:45Z - Sysnative Powershell will be used to access the registry.
2024-05-13 08:28:47Z - Current version: v4.7.4.
2024-05-13 08:28:47Z - Starting upgrade processs.
2024-05-13 08:29:07Z - Restarting Wazuh-Agent service.
2024-05-13 08:29:07Z - Installation finished.
2024-05-13 08:29:07Z - Process ID: 520.
2024-05-13 08:29:22Z - Reading status file: status='connected'.
2024-05-13 08:29:22Z - Upgrade finished successfully.
2024-05-13 08:29:22Z - New version: v4.9.0.
```
- WPK fail:
```
2024-05-13 16:21:47Z - Sysnative Powershell will be used to access the registry.
2024-05-13 16:21:47Z - Current version: v4.7.4.
2024-05-13 16:21:47Z - Generating backup.
2024-05-13 16:21:47Z - Backing up Wazuh home files.
2024-05-13 16:21:48Z - Searching Wazuh-Agent cached MSI through the registry.
2024-05-13 16:21:50Z - Backing up Wazuh-Agent cached MSI: "C:\Windows\Installer\109acbba.msi".
2024-05-13 16:21:50Z - Trying to stop Wazuh service.
2024-05-13 16:21:52Z - Starting upgrade processs.
2024-05-13 16:21:54Z - Restarting Wazuh-Agent service.
2024-05-13 16:21:54Z - Installation finished.
2024-05-13 16:21:54Z - Process ID: 592.
2024-05-13 16:22:14Z - Reading status file: status=''.
2024-05-13 16:22:14Z - Upgrade failed: Restoring former installation.
2024-05-13 16:22:16Z - Trying to stop Wazuh service.
2024-05-13 16:22:18Z - Performing the Wazuh-Agent uninstall using: "MsiExec.exe /X{EC4699DC-76B1-43D2-8E0D-E5B317608238} /quiet /norestart".
2024-05-13 16:22:27Z - Excecuting former Wazuh-Agent MSI: ".\backup\109acbba.msi".
2024-05-13 16:22:30Z - Restoring former Wazuh-Agent home files.
2024-05-13 16:22:30Z - Current version: v4.7.4.
2024-05-13 16:22:30Z - Installing Wazuh service.
2024-05-13 16:22:30Z - Starting Wazuh-Agent service.
```

As you can see, the behaviour is as expected.
The problem with this kind of issues is that they usually happen because of a bug during the upgrade phase, and the error shown in this issue is a consequence of that unknown bug, we would need to know more about what happened punctually (we have already found some cases like connection problems during the upgrade) to solve it.
I have done some research related to this log, I haven't found any relevant information. 
For the moment I think this issue can be closed, but if any new relevant information is discovered or the problem can be reproduced, we will reopen it and continue the investigation!

**Comment by MarcelKemp** [comment] 2024-05-14 10:37
As Jose said, we are closing the issue. 
If the problem appears again, do not hesitate to reopen it, although we would need enough information to replicate it or to have the environment where it fails.

**Closed by MarcelKemp** 2024-05-14 10:37 UTC
Labels: msi, windows, level/task, reporter/community, type/bug, module/install
