### ISSUE TITLE
OVA takes too long to start

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2357] opened 2023-08-16 17:41 UTC
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| At least 4.5.1 RC1|OVA | Start | PopOS |

- When testing the OVA 4.5.1 RC1, an unwanted behavior was found when starting the OVA, since it takes too long to show the system login, up to 5 minutes, it is necessary to investigate what makes the OVA take so long to start
- The same behavior occurs with the 4.5.0 OVA
- VirtualBox version: 6.1

<details><summary>Host info</summary>

- RAM used at the moment to start the VM: 16GB

```
╰─➤  cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

</details>

**Comment by vcerenu** [comment] 2023-08-16 20:16
I did a test to import and run the OVA inside a VM with PopOS and it finished successfully, taking 2 minutes to start it and taking into account that the PopOS VM had 4 cores assigned to my notebook and the OVA had only 1 assigned inside

In the image I show in a PopOS terminal the start time of the VM (GMT -3) and inside the Wazuh OVA VM I take the time after logging in (GMT)

![image](https://github.com/wazuh/wazuh-packages/assets/56500015/f56c37ae-42e0-400f-b8e5-254d594b541f)

The delay may be due to some issue within the host machine where the OVA is running, considering that we haven't had any issues with OVA 4.5.0 and haven't received any inquiries from the community about it either.

**Comment by vcerenu** [comment] 2023-08-22 20:28
Several tests were carried out since the startup time improved a bit, but it continues to generate delays, the GRUB that we had configured for Centos 7 was modified and tests are being carried out

**Comment by vcerenu** [comment] 2023-08-23 20:18
Added some options that come by default in the Amazon Linux 2 image, but at boot time it generated a Kernel Panic:

![image](https://github.com/wazuh/wazuh-packages/assets/56500015/42bd7ddf-4878-4583-acf4-81deedc5d2d1)

The error was verified and it was due to the fact that it did not have the path of the root directory inside the startup, so the parameter was modified and the OS was successfully started:

![image](https://github.com/wazuh/wazuh-packages/assets/56500015/7dac9004-50d1-4c69-aff0-18cc23c5be14)

A new OVA is being generated with these parameters to be able to test its correct functioning

**Comment by vcerenu** [comment] 2023-08-24 19:47
A new OVA was created with the new parameters and a successful startup test was performed, both on a Windows host and within an Ubuntu VM. In both cases the startup was acceptable (30 sec on the windows host and 1:30 on the ubuntu host) and no errors were found.

Tests are carried out on other Hosts to verify that the operation is correct

**Comment by vcerenu** [comment] 2023-08-25 15:39
Reviewed OVA GRUB changes and working properly, reviewed startup on various operating systems and found no delays or errors.

The slowness found by Raul corresponds to a network problem on his computer, a meeting was held to review the problem since we had tested with the same configuration on other hosts and we did not have the same slowness problems and we found that he had a problem with his network, which caused the OVA to have delays, the network used was modified and the delays disappeared, so we confirmed that the delay was not due to a problem with the OVA itself

**Closed** 2023-08-28 19:37 UTC
Labels: level/task, type/bug
