### ISSUE TITLE
SSL Certificate Verification Failure when Downloading wazuh-agent.spec

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh-packages#2889] opened 2024-03-26 13:21 UTC
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.8.0 | Agent | Install/Upgrade/Remove | Centos 5 |

### Description

Currently, attempts to download the `wazuh-agent.spec` file using cURL encounter an SSL certificate verification failure. This issue prevents the successful retrieval of the file, which is essential for building RPM packages for the Wazuh agent in centos 5. The error message indicates a problem with verifying the legitimacy of the server's SSL certificate, resulting in a failed connection establishment.

### Definition of Done

- The SSL certificate verification failure is resolved, enabling the successful download of the `wazuh-agent.spec` file using cURL.
- Testing confirms that the updated cURL command or configuration successfully retrieves the spec file without SSL certificate verification errors.

```
+ curl -L https://raw.githubusercontent.com/wazuh/wazuh-packages/4.8.0/rpms/SPECS/wazuh-agent.spec -o /downloaded_tmp_specs/wazuh-agent.spec
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.


```

**Comment by rafabailon** [comment] 2024-04-08 13:02
In the issue [Release 4.8.0 - Beta 5 - Upgrade metrics](https://github.com/wazuh/wazuh/issues/22817) this error has appeared again in CentOS 5. I have tried relaunching the pipeline without success.

I reopen the issue to review the error. I also leave the builds in case they are necessary in the investigation.

First Build:

- CentOS 5 (3.13.6): https://ci.wazuh.info/job/Test_upgrade/134426/
- CentOS 5 (4.6.0): https://ci.wazuh.info/job/Test_upgrade/134402/
- CentOS 5 (4.7.3): https://ci.wazuh.info/job/Test_upgrade/134376/

Relaunch:

- CentOS 5 (3.13.6): https://ci.wazuh.info/job/Test_upgrade/134448/
- CentOS 5 (4.6.0): https://ci.wazuh.info/job/Test_upgrade/134449/
- CentOS 5 (4.7.3): https://ci.wazuh.info/job/Test_upgrade/134450/

**Comment by MarcelKemp** [comment] 2024-04-09 10:10
After researching it, the problem is in the jenkins repository, because the `curl` commands used for _CentOS 5_ lack the `-k` flag to avoid checking certificates. Therefore, I proceed to close this issue, as it is reflected in this other issue:
- https://github.com/wazuh/wazuh-jenkins/issues/6390

**Closed by MarcelKemp** 2024-04-09 10:10 UTC
Labels: level/task, type/bug
